
services:

  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./webpage
    labels:
      - "traefik.http.routers.frontend.rule=Host(`linguexplorer.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

    expose:
      - "80"
    restart: always
    